apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-nextjs
  labels:
    app: dummy-nextjs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-nextjs
  template:
    metadata:
      labels:
        app: dummy-nextjs
    spec:
      containers:
        - name: dummy-nextjs
          image: "tomica1911/dummy-nextjs:1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
