apiVersion: v1
kind: Service
metadata:
  name: dummy-nextjs-test
  labels:
    app: dummy-nextjs-test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
      app: dummy-nextjs
