apiVersion: v1
kind: Service
metadata:
  name: dummy-nextjs
  labels:
    dummy-nextjs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    dummy-nextjs
